const $ = (selector) => document.querySelector(selector);
const ui = { strip: $('#tabStrip'), stack: $('#frameStack'), empty: $('#emptyState'), input: $('#addressInput'), tabDialog: $('#tabDialog'), menu: $('#contextMenu'), tooltip: $('#tabTooltip'), scrollPrev: $('#tabScrollPrev'), scrollNext: $('#tabScrollNext') };
let tabs = [], activeId = null, editId = null, contextId = null, settings = { showAddressBar: false, compactTabs: true, showPinIcon: true, showRefreshButton: false, showLoadingIndicator: true, theme: 'system', home: { title: 'My Home', url: '', pinned: false } }, selectedIds = new Set(), lastSelectedIndex = null, loadingIds = new Set(), tooltipTimer = null, spacePressed = false, panningTabs = false, tabPanMoved = false, tabPanStartX = 0, tabPanStartLeft = 0;

function normalizeUrl(value) { const input = value.trim(); if (!input) return ''; if (/^https?:\/\//i.test(input)) return input; if (/^[\w.-]+\.[a-z]{2,}(\/|$)/i.test(input)) return `https://${input}`; return `https://www.google.com/search?q=${encodeURIComponent(input)}`; }
function applyTheme() { document.documentElement.dataset.theme = settings.theme === 'system' ? '' : settings.theme; }
async function persist() { await chrome.storage.local.set({ panelTabs: tabs, activePanelTab: activeId }); }
function launchHomeTab() { const url = settings.home?.url ? normalizeUrl(settings.home.url) : chrome.runtime.getURL('welcome.html'); return { id: crypto.randomUUID(), title: settings.home?.title || 'Welcome to WebPanel', url, pinned: !!settings.home?.pinned }; }
async function init() { const [data, session] = await Promise.all([chrome.storage.local.get(['panelTabs', 'activePanelTab', 'panelSettings']), chrome.storage.session.get('openHomeOnNextPanel')]); tabs = Array.isArray(data.panelTabs) ? data.panelTabs : []; settings = { ...settings, ...data.panelSettings, openHomeOnLaunch: true, home: { ...settings.home, ...data.panelSettings?.home } }; const shouldOpenHome = session.openHomeOnNextPanel && settings.openHomeOnLaunch; if (session.openHomeOnNextPanel) await chrome.storage.session.remove('openHomeOnNextPanel'); if (shouldOpenHome) { const home = launchHomeTab(), existing = tabs.find(tab => tab.url === home.url); activeId = existing?.id || home.id; if (!existing) tabs.push(home); await chrome.storage.local.set({ panelTabs: tabs, activePanelTab: activeId }); } else { activeId = tabs.some(t => t.id === data.activePanelTab) ? data.activePanelTab : tabs[0]?.id || null; } if (activeId) { selectedIds.add(activeId); loadingIds.add(activeId); } render(); }
function activeTab() { return tabs.find(t => t.id === activeId); }
function showFrame(tab) { ui.stack.querySelectorAll('iframe').forEach(frame => frame.classList.remove('visible')); if (!tab) return; let frame = ui.stack.querySelector(`iframe[data-tab-id="${tab.id}"]`); if (!frame) { frame = document.createElement('iframe'); frame.dataset.tabId = tab.id; frame.dataset.url = tab.url; frame.title = tab.title; frame.referrerPolicy = 'no-referrer'; frame.allow = 'camera; microphone'; frame.addEventListener('load', () => { loadingIds.delete(tab.id); render(); }); frame.src = tab.url; ui.stack.append(frame); } else if (frame.dataset.url !== tab.url) { frame.dataset.url = tab.url; frame.src = tab.url; } frame.classList.add('visible'); }
function refreshTab(id) { const frame = ui.stack.querySelector(`iframe[data-tab-id="${id}"]`); if (frame) { loadingIds.add(id); frame.src = frame.src; render(); } }
function render() { ui.strip.replaceChildren(); document.querySelector('.panel-shell').classList.toggle('compact', settings.compactTabs); tabs.forEach((tab, index) => { const b = document.createElement('button'); b.className = `panel-tab ${tab.id === activeId ? 'active' : ''} ${selectedIds.has(tab.id) ? 'selected' : ''}`; b.setAttribute('role','tab'); b.dataset.id = tab.id; b.innerHTML = `<span class="tab-title"></span>${tab.pinned && settings.showPinIcon ? '<span class="pin" aria-label="Pinned">⌖</span>' : ''}${loadingIds.has(tab.id) && settings.showLoadingIndicator ? '<span class="tab-loader" aria-label="Loading"></span>' : ''}${settings.showRefreshButton ? '<span class="tab-refresh" role="button" aria-label="Refresh this tab" title="Refresh">↻</span>' : ''}`; b.querySelector('.tab-title').textContent = tab.title; b.addEventListener('click', (e) => select(tab.id, index, e.shiftKey)); b.addEventListener('contextmenu', (e) => showMenu(e, tab.id)); const refresh = b.querySelector('.tab-refresh'); if (refresh) refresh.addEventListener('click', e => { e.stopPropagation(); refreshTab(tab.id); }); b.addEventListener('mouseenter', () => showTooltip(b, tab)); b.addEventListener('mouseleave', hideTooltip); b.addEventListener('focus', () => showTooltip(b, tab)); b.addEventListener('blur', hideTooltip); ui.strip.append(b); }); const active = activeTab(); $('#addressForm').classList.toggle('hidden', !settings.showAddressBar); ui.input.value = active?.url || ''; ui.empty.classList.toggle('hidden', !!active); showFrame(active); }
function showTooltip(button, tab) { clearTimeout(tooltipTimer); tooltipTimer = setTimeout(() => { ui.tooltip.querySelector('strong').textContent = tab.title; ui.tooltip.querySelector('.tooltip-state').textContent = tab.pinned ? 'Pinned tab' : 'Not pinned'; ui.tooltip.querySelector('.tooltip-url').textContent = tab.url; const rect = button.getBoundingClientRect(); ui.tooltip.style.left = `${Math.max(8, Math.min(rect.left, innerWidth - 318))}px`; ui.tooltip.style.top = `${Math.min(rect.bottom + 8, innerHeight - 88)}px`; ui.tooltip.classList.add('show'); }, 500); }
function hideTooltip() { clearTimeout(tooltipTimer); ui.tooltip.classList.remove('show'); }
async function select(id, index, extend = false) { activeId = id; if (!ui.stack.querySelector(`iframe[data-tab-id="${id}"]`)) loadingIds.add(id); if (extend && lastSelectedIndex !== null) { const [start, end] = [lastSelectedIndex, index].sort((a, b) => a - b); for (let i = start; i <= end; i++) selectedIds.add(tabs[i].id); } else { selectedIds = new Set([id]); lastSelectedIndex = index; } await persist(); render(); }
function showMenu(e, id) { e.preventDefault(); contextId = id; if (!selectedIds.has(id)) { selectedIds = new Set([id]); lastSelectedIndex = tabs.findIndex(tab => tab.id === id); render(); } ui.menu.style.left = `${Math.min(e.clientX, innerWidth - 155)}px`; ui.menu.style.top = `${Math.min(e.clientY, innerHeight - 180)}px`; $('#menuDismissLayer').classList.add('show'); ui.menu.classList.add('show'); }
function closeMenu() { ui.menu.classList.remove('show'); $('#menuDismissLayer').classList.remove('show'); }
function openTabDialog(tab) { editId = tab?.id || null; $('#dialogTitle').textContent = tab ? 'Edit tab' : 'New tab'; $('#tabName').value = tab?.title || ''; $('#tabUrl').value = tab?.url || 'https://'; $('#tabPinned').checked = tab?.pinned ?? true; ui.tabDialog.showModal(); $('#tabName').focus(); }
async function openNewTabPage() { const tab = { id: crypto.randomUUID(), title: 'Add New Tab', url: chrome.runtime.getURL('newtab.html'), pinned: false }; tabs.push(tab); activeId = tab.id; selectedIds = new Set([tab.id]); loadingIds.add(tab.id); await persist(); render(); }
$('#addTab').onclick = openNewTabPage; $('#emptyAdd').onclick = openNewTabPage;
ui.scrollPrev.onclick=()=>ui.strip.scrollBy({left:-180,behavior:'smooth'});ui.scrollNext.onclick=()=>ui.strip.scrollBy({left:180,behavior:'smooth'});ui.strip.addEventListener('wheel',event=>{if(!event.deltaY)return;event.preventDefault();ui.strip.scrollLeft+=event.deltaY;},{passive:false});document.addEventListener('keydown',event=>{if(event.code==='Space'&&!/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement?.tagName))spacePressed=true;});document.addEventListener('keyup',event=>{if(event.code==='Space')spacePressed=false;});window.addEventListener('blur',()=>spacePressed=false);ui.strip.addEventListener('pointerdown',event=>{if(!spacePressed)return;panningTabs=true;tabPanMoved=false;tabPanStartX=event.clientX;tabPanStartLeft=ui.strip.scrollLeft;ui.strip.setPointerCapture(event.pointerId);ui.strip.classList.add('is-panning');event.preventDefault();});ui.strip.addEventListener('pointermove',event=>{if(!panningTabs)return;const delta=event.clientX-tabPanStartX;if(Math.abs(delta)>4)tabPanMoved=true;ui.strip.scrollLeft=tabPanStartLeft-delta;});ui.strip.addEventListener('pointerup',event=>{if(!panningTabs)return;panningTabs=false;ui.strip.classList.remove('is-panning');if(ui.strip.hasPointerCapture(event.pointerId))ui.strip.releasePointerCapture(event.pointerId);});ui.strip.addEventListener('click',event=>{if(!tabPanMoved)return;event.preventDefault();event.stopPropagation();tabPanMoved=false;},true);
$('#tabForm').addEventListener('submit', async (e) => { e.preventDefault(); const url = normalizeUrl($('#tabUrl').value); if (!url) return; const item = { id: editId || crypto.randomUUID(), title: $('#tabName').value.trim() || 'Untitled tab', url, pinned: $('#tabPinned').checked }; if (editId) { tabs = tabs.map(t => t.id === editId ? item : t); loadingIds.add(item.id); } else { tabs.push(item); activeId = item.id; loadingIds.add(item.id); } await persist(); ui.tabDialog.close(); render(); });
$('#addressForm').addEventListener('submit', async (e) => { e.preventDefault(); const tab = activeTab(), url = normalizeUrl(ui.input.value); if (!tab || !url) return; tab.url = url; loadingIds.add(tab.id); await persist(); render(); });
$('#homeBtn').onclick = () => { const home = settings.home; const tab = activeTab(); if (tab && home?.url) { tab.url = normalizeUrl(home.url); tab.title = home.title || 'My Home'; tab.pinned = !!home.pinned; loadingIds.add(tab.id); persist().then(render); } };
ui.menu.addEventListener('click', async (e) => { const action = e.target.dataset.action, tab = tabs.find(t => t.id === contextId); closeMenu(); if (!action || !tab) return; if (action === 'refresh') { selectedIds.forEach(refreshTab); return; } if (action === 'edit') openTabDialog(tab); if (action === 'duplicate') { const copy = { ...tab, id: crypto.randomUUID(), title: `${tab.title} copy`, pinned: true }; tabs.push(copy); activeId = copy.id; selectedIds = new Set([copy.id]); await persist(); render(); } if (action === 'pin' || action === 'unpin') { tabs = tabs.map(item => selectedIds.has(item.id) ? { ...item, pinned: action === 'pin' } : item); await persist(); render(); } if (action === 'remove') { const locked = tabs.filter(item => selectedIds.has(item.id) && item.pinned); if (locked.length) { alert('Pinned tabs cannot be removed. Unpin them first.'); return; } tabs = tabs.filter(item => !selectedIds.has(item.id)); if (!tabs.some(item => item.id === activeId)) activeId = tabs[0]?.id || null; selectedIds = activeId ? new Set([activeId]) : new Set(); await persist(); render(); } });
$('#menuDismissLayer').addEventListener('pointerdown', closeMenu);
document.addEventListener('click', (e) => { if (!ui.menu.contains(e.target)) closeMenu(); }); document.addEventListener('keydown', e => { if (e.key === 'Escape') closeMenu(); }); document.querySelectorAll('[data-close]').forEach(b => b.onclick = () => b.closest('dialog').close());
chrome.storage.onChanged.addListener((changes, area) => { if (area === 'local' && changes.panelSettings) { settings = { ...settings, ...changes.panelSettings.newValue }; applyTheme(); render(); } });
window.addEventListener('message', async event => { if (event.source !== ui.stack.querySelector('iframe.visible')?.contentWindow || event.data?.type !== 'webpanel-set-home') return; const url = normalizeUrl(event.data.url); if (!url) return; const home = { title: event.data.title || 'My Home', url, pinned: false }; settings = { ...settings, home }; const tab = activeTab(); if (tab) { tab.title = home.title; tab.url = home.url; tab.pinned = home.pinned; loadingIds.add(tab.id); } await chrome.storage.local.set({ panelSettings: settings, panelTabs: tabs, activePanelTab: activeId }); render(); });
window.addEventListener('message', async event => { const frame = [...ui.stack.querySelectorAll('iframe')].find(item => item.contentWindow === event.source); if (!frame || !frame.dataset.url.startsWith(chrome.runtime.getURL(''))) return; if (event.data?.type === 'webpanel-open-settings') { await chrome.runtime.openOptionsPage(); return; } if (event.data?.type !== 'webpanel-add-tab') return; const url = normalizeUrl(event.data.url); if (!url) return; const tab = tabs.find(item => item.id === frame.dataset.tabId); if (!tab) return; tab.title = event.data.title || 'Untitled tab'; tab.url = url; tab.pinned = !!event.data.pinned; activeId = tab.id; loadingIds.add(tab.id); await persist(); render(); });
init().then(applyTheme);
